### ISSUE TITLE
Invalid rect type in collision

### ISSUE THREAD

**Issue by Aston7292** [dille12/OVRDOZE#46]
I noticed that if moving and colliding with a zombie at the same time the game will crash with this error:
level.py, line 609, in checkcollision
    collider = pygame.Rect(
               ^^^^^^^^^^^^
TypeError: Argument must be rect style object

The proble seems to be that the player position will sometimes contain a numpy float instead of a regular float and i'm pretty sure this could also cause errors in other parts of the Map class.

**Comment by dille12** [comment]
That's weird, did you encounter this on the .exe frozen version or did you clone the repository?

**Comment by Aston7292** [comment]
i cloned the repo

**Comment by dille12** [comment]
I guess it's because of wrong pygame or python version, are you running python 3.10 and pygame >= 2.1.2?

**Comment by Aston7292** [comment]
I'm on python 3.12.4 and pygame 2.5.1, i have no clue why this happens only to me, however i was able to track down my issue, on line 1922 of game.py yhe variable bloodVal is gotten from a numpy array of floats16 then this variable is used in many calculations including player_pos, it becomes a float16 and crashes when using it to create a rect, i just casted bloodVal to float and now it works completly fine

**Comment by dille12** [comment]
Ok I'm pretty sure this is a dependency error so if you could type "pip list" to your cmd and paste it here i'll try to replicate it. 
Did the whole game work after that fix?

**Comment by Aston7292** [comment]
Here's everything i have:
`altgraph`                  0.17.4
audioread                 3.0.1
certifi                   2024.7.4
cffi                      1.17.0
charset-normalizer        3.3.2
colorama                  0.4.6
contourpy                 1.2.1
cycler                    0.12.1
decorator                 5.1.1
EasyProcess               1.1
entrypoint2               1.1
filelock                  3.15.4
fonttools                 4.53.1
freetype-py               2.4.0
fsspec                    2024.6.1
glfw                      2.7.0
idna                      3.7
imageio                   2.35.1
imageio-ffmpeg            0.5.1
intel-cmplr-lib-ur        2024.2.1
intel-openmp              2024.2.1
Jinja2                    3.1.4
joblib                    1.4.2
keyboard                  0.13.5
kiwisolver                1.4.5
lazy_loader               0.4
librosa                   0.10.2.post1
line_profiler             4.1.3
llvmlite                  0.43.0
MarkupSafe                2.1.5
matplotlib                3.9.2
memory-profiler           0.61.0
mkl                       2024.2.1
MouseInfo                 0.1.3
moviepy                   1.0.3
mpmath                    1.3.0
msgpack                   1.0.8
mss                       9.0.1
mypy                      1.11.1
mypy-extensions           1.0.0
networkx                  3.3
numba                     0.60.0
numpy                     2.0.0
packaging                 24.1
pefile                    2023.2.7
pillow                    10.4.0
pip                       24.2
platformdirs              4.2.2
pooch                     1.8.2
proglog                   0.1.10
psutil                    6.0.0
PyAutoGUI                 0.9.54
pycparser                 2.22
pygame-ce                 2.5.1
PyGetWindow               0.0.9
pyinstaller               6.10.0
pyinstaller-hooks-contrib 2024.8
PyMsgBox                  1.0.9
pynput                    1.7.7
PyOpenGL                  3.1.7
PyOpenGL-accelerate       3.1.7
pyparsing                 3.1.2
pyperclip                 1.9.0
PyRect                    0.2.0
pyscreenshot              3.1
PyScreeze                 0.1.30
python-dateutil           2.9.0.post0
PyTMX                     3.32
pytube                    15.0.0
pytweening                1.2.0
pywin32                   306
pywin32-ctypes            0.2.3
PyYAML                    6.0.2
requests                  2.32.3
scikit-learn              1.5.1
scipy                     1.14.0
screeninfo                0.8.1
setuptools                73.0.0
six                       1.16.0
soundfile                 0.12.1
soxr                      0.4.0
sympy                     1.13.2
tbb                       2021.13.1
termstyle                 0.1.11
threadpoolctl             3.5.0
tqdm                      4.66.5
typing_extensions         4.12.2
UPnPy                     1.1.8
urllib3                   2.2.2
wheel                     0.44.0`
After changing that line i haven't encountered any other problems

**Comment by dille12** [comment]
Thank you! If you want, you can do a pull request for that line if it fixes everything

**Comment by dille12** [comment]
Okay I tested with these library versions and it's the newer numpy version that's causing the issue.
